/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_bsc_tools_extrae_Wrapper */

#ifndef _Included_es_bsc_tools_extrae_Wrapper
#define _Included_es_bsc_tools_extrae_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Init
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Fini
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    GetTaskId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_tools_extrae_Wrapper_GetTaskId
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    GetPID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_tools_extrae_Wrapper_GetPID
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Event
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Event
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    nEvent
 * Signature: ([I[J)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_nEvent
  (JNIEnv *, jclass, jintArray, jlongArray);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Comm
 * Signature: (ZIIIJ)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Comm
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jlong);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    SetOptions
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_SetOptions
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Pause
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    Resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_Resume
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    SetID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_SetID
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    SetNumTasks
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_SetNumTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    GetID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_tools_extrae_Wrapper_GetID
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    GetNumTasks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_tools_extrae_Wrapper_GetNumTasks
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    PushIDsDown
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_PushIDsDown
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    StartSnifferLowLevel
 * Signature: (Z[I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_StartSnifferLowLevel
  (JNIEnv *, jclass, jboolean, jintArray);

/*
 * Class:     es_bsc_tools_extrae_Wrapper
 * Method:    StartPortMapperLowLevel
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_tools_extrae_Wrapper_StartPortMapperLowLevel
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
